backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "網站內容"
    files:
      - file: "index.html"
        label: "首頁"
        name: "home"
        fields:
          - { label: "標題", name: "title", widget: "string" }